# Generated by Django 3.1.2 on 2020-10-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201015_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('votepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.question')),
            ],
        ),
    ]
