# Generated by Django 3.1.2 on 2020-10-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201017_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_value',
        ),
    ]
