# Generated by Django 3.1.2 on 2020-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_value',
            field=models.BooleanField(default=0),
        ),
    ]
