# Generated by Django 3.1.2 on 2020-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20201017_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='gay@mail.ru', max_length=254),
        ),
    ]
